# Generated by Django 6.0.2 on 2026-03-04 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_user_test_doctor_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antibiotic',
            name='effectiveness',
        ),
        migrations.RemoveField(
            model_name='bacteria',
            name='description',
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_years',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hospital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacteria', models.CharField(max_length=200)),
                ('antibiotic', models.CharField(max_length=200)),
                ('prediction', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
