# Generated by Django 4.2.16 on 2026-03-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
