# Generated by Django 4.2.16 on 2026-03-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_sample_additional_notes_sample_sample_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.patient'),
        ),
    ]
