# Generated by Django 4.2.16 on 2026-03-15 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_sample_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrecord',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='testrecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.patient'),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.sample'),
        ),
    ]
