# Generated by Django 4.2.16 on 2026-03-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_patient_address_patient_city_patient_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
