# Generated by Django 6.0.2 on 2026-03-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_test_antibiotic_name_test_result'),
        ('user', '0014_test_antibiotic_name_test_result'),
    ]

    operations = [
    ]
